In [1]:
# Import Dependencies
import pandas as pd

In [10]:
Zillow_values = "Resources/Zillow_values.csv"
Zillow2023 = "Resources/AZZillow2023.csv"

In [11]:
Zillow_values_df = pd.read_csv(Zillow_values)
Zillow2023_df = pd.read_csv(Zillow2023)

In [12]:
Zillow_values_df.head(10)

   Zipcode  Zillow_value_per_Zip
0    85003           584908.2331
1    85004           445080.8570
2    85006           418856.7727
3    85007           414950.5322
4    85008           364850.4607
5    85009           285493.7243
6    85012           668437.4812
7    85013           486583.8996
8    85014           434795.7069
9    85015           347868.1627

In [13]:
Zillow2023_df.head(12)

,State,City,Street,Zipcode,Bedroom,Bathroom,Area,PPSq,LotArea,Latitude,Longitude,ListedPrice
0,AZ,Phoenix,N Dayton St,85006,2,2.0,1855,256.064690,0.145087,33.071648,-111.454926,475000
1,AZ,Phoenix,W Lynwood St,85007,2,3.0,2423,531.985142,0.980000,34.590916,-112.444150,1289000
2,AZ,Phoenix,W Virginia Ave,85009,4,2.0,1706,199.296014,0.280000,32.194954,-110.870460,339999
3,AZ,Phoenix,E Tuckey Ln,85012,4,3.0,2827,256.455607,0.175000,33.448963,-111.671280,725000
4,AZ,Phoenix,W Roma Ave,85013,1,1.0,704,383.522727,0.670000,34.731953,-111.995346,270000
5,AZ,Phoenix,N 13th Pl,85014,3,2.0,1454,299.105915,0.108081,33.850014,-112.096750,434900
6,AZ,Phoenix,E Ocotillo Rd,85014,6,6.0,6429,699.953336,0.471166,35.159450,-111.634120,4500000
7,AZ,Phoenix,N Longview Ave,85014,5,2.0,2040,188.725490,0.099977,33.397583,-111.752014,385000
8,AZ,Phoenix,N Longview Ave,85014,2,2.0,1120,302.678571,0.230000,34.516693,-114.299500,339000
9,AZ,Phoenix,N 10th Way,85014,5,3.0,3058,359.712230,0.290000,34.490780,-114.342155,1100000
10,AZ,Phoenix,W Whitton Ave,85015,4,2.0,2260,210.176991,0.170000,32.377716,-111.125870,475000
11,AZ,Phoenix,E Weldon Ave,85016,4,5.0,4518,265.604250,0.940000,32.320312,-110.945950,1200000

In [14]:
Zillow = pd.merge(Zillow_values_df, Zillow2023_df, on='Zipcode', how='inner')
Zillow.head(13)

,Zipcode,Zillow_value_per_Zip,State,City,Street,Bedroom,Bathroom,Area,PPSq,LotArea,Latitude,Longitude,ListedPrice
0,85006,418856.7727,AZ,Phoenix,N Dayton St,2,2.0,1855,256.064690,0.145087,33.071648,-111.454926,475000
1,85007,414950.5322,AZ,Phoenix,W Lynwood St,2,3.0,2423,531.985142,0.980000,34.590916,-112.444150,1289000
2,85009,285493.7243,AZ,Phoenix,W Virginia Ave,4,2.0,1706,199.296014,0.280000,32.194954,-110.870460,339999
3,85012,668437.4812,AZ,Phoenix,E Tuckey Ln,4,3.0,2827,256.455607,0.175000,33.448963,-111.671280,725000
4,85013,486583.8996,AZ,Phoenix,W Roma Ave,1,1.0,704,383.522727,0.670000,34.731953,-111.995346,270000
5,85014,434795.7069,AZ,Phoenix,N 13th Pl,3,2.0,1454,299.105915,0.108081,33.850014,-112.096750,434900
6,85014,434795.7069,AZ,Phoenix,E Ocotillo Rd,6,6.0,6429,699.953336,0.471166,35.159450,-111.634120,4500000
7,85014,434795.7069,AZ,Phoenix,N Longview Ave,5,2.0,2040,188.725490,0.099977,33.397583,-111.752014,385000
8,85014,434795.7069,AZ,Phoenix,N Longview Ave,2,2.0,1120,302.678571,0.230000,34.516693,-114.299500,339000
9,85014,434795.7069,AZ,Phoenix,N 10th Way,5,3.0,3058,359.712230,0.290000,34.490780,-114.342155,1100000
10,85015,347868.1627,AZ,Phoenix,W Whitton Ave,4,2.0,2260,210.176991,0.170000,32.377716,-111.125870,475000
11,85016,507496.7530,AZ,Phoenix,E Weldon Ave,4,5.0,4518,265.604250,0.940000,32.320312,-110.945950,1200000
12,85017,310600.5399,AZ,Phoenix,W Solano Dr S,2,3.0,1612,325.682382,1.030000,32.282710,-110.888610,525000

In [15]:
Zillow.to_csv("Zillow.csv")